strand = "AAGCCGCGCCGCGGGTACTTTGATACCCATACCTACAACTGGCAAAACCGGGACTGTATCGATGTGACCTATATGGTCTGGGGTCTCATTCAATACATGGTGGACTGGGCTAGCGGAAGACGCCTCAGGTGCGCTATCCGTACGGTCCTTCCTGGAGGTCCCGGCGGAAGAGTGGGGTAAGTGCTGGGATGGTGCAACGCTAGTGCCTTTGTCGTTGGAGGTACTATCAGCCAAGAGGCATCGAAGCCAATGGATTCAGCGCCGCTACATTAACACACCCCGACGATTAACTCTGCGCCAAGCCGATTCCGCTGGGTTGGTGGACTTGGTATAGTGGGAAACTGAGCGTGTCGCTAAATGGGTGCGCATAGTTAGTCTGCTACTAACTTGCGAAGTGCTCGCACATAAACCTTGGGACGGAATGCTTCCCCAGGTCCTTGCACTCCTCACCGTAAGTTCTATCGTGGTTCAGTCGGTTTTCCTTGAGCCATTTCTTAGAGGTGTCACACTGAGTGCCGACATACCATTGTCAGAAGTAAGGAAAGCCGAATGCAGTCAATCAACACTTGGGCTTCATAATAGGCTACGTTAATGATACCCATACATCGTGATACGATTCATCGCAGGGTACGGATGCGAGTCAAGGTTAGTCTTTCTCCACATATGCCCGCGGGCCGATCTGTACACCGAACGCTAACAAGCCTCGCGTCAAGTGGGCAGTCCTGCAAACATCCGGTGGTTTCTAAGAGCACCGGTTAGTTGACCATTGGACGAGCCGTCCTCGGCGTATTCCAACAGCTTCCTCGAGAGAATACGTTGACTGAAAAAGACGTAAGTAAAGCGTGCGTTAATGCTATAATAAAGTGGCCGGG"

#This code is designed to count each nucleotide (A, C, G, and T) in the strand of DNA.
print("Counts of each nucleotide: A, C, G, T: ")
print(str(strand.count("A")) + " " + str(strand.count("C")) + " " + str(strand.count("G")) + " " + str(strand.count("T")))


#This code should do the exact same thing with f-string literals
g_count =strand.count("G")
c_count =strand.count("C")
t_count = strand.count("T")
a_count = strand.count("A")
print(f"{a_count} {c_count} {g_count} {t_count}")
